name: Chroma64 Pipeline
on:
  push:
    branches: [ master, feature_* ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1
    - name: Restore dotnet tools
      uses: xt0rted/dotnet-tool-restore@v1
    - name: Run dotnet format
      uses: xt0rted/dotnet-format@v1
      with:
        version: 4
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
